// <auto-generated />
namespace loginPage_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class loginpagemigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginpagemigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202306250114247_loginpagemigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
